### ISSUE TITLE
Switching from a non dev release to a dev release fails

### ISSUE THREAD

**Issue by beyhan** [dpb587/bosh-release-resource#3]
If you use the resource without the option `dev_release: true` it will not create dev releases. Switching to this option afterwards, when the resource already created some versions will cause a failure in [here](https://github.com/dpb587/bosh-release-resource/blob/5b955ece02ef609bd4012c4e54b1c7aed178404b/check/main.go#L59) with `index out of range`.

**Comment by dpb587** [comment]
Thanks - I added a safety check to avoid the panic that happens to support switching, too. Still might be some edge cases when trying to switch, so, in general, might be better to use different resource names.
