### ISSUE TITLE
Creating a dev release doesn't work with a symlink

### ISSUE THREAD

**Issue by beyhan** [dpb587/bosh-release-resource#4]
Creation of the dev release fails with the following error:

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
fatal: Path 'releases/bosh/index.yml' exists on disk, but not in '67b0c30'.
check: bad release: versions: loading releases index.yml for 67b0c30: exit status 128
```

There is a problem with the symlink under `releases/bosh`.

**Comment by dpb587** [comment]
Thanks - I added a slightly hacky workaround for now. Following symlinks with raw git commands and no checkout requires a fair bit of work. Might be something that can be improved in the future.

Also, the bosh repo could/should be updated to not use symlinks at some point, too, but I thought that might take some time to make its way through branches.
